const personas = [
  {
    id: 1,
    nombre: "Lucía",
    apellido: "Gómez",
    edad: 28,
    genero: "Femenino",
    email: "lucia.gomez@example.com",
    telefono: "1123456789",
    direccion: "Calle Falsa 123",
    ciudad: "Buenos Aires",
    pais: "Argentina",
    estadoCivil: "Soltera",
    profesion: "Diseñadora gráfica"
  },
  {
    id: 2,
    nombre: "Juan",
    apellido: "Pérez",
    edad: 35,
    genero: "Masculino",
    email: "juan.perez@example.com",
    telefono: "1123987654",
    direccion: "Av. Rivadavia 4567",
    ciudad: "Córdoba",
    pais: "Argentina",
    estadoCivil: "Casado",
    profesion: "Ingeniero"
  },
  {
    id: 3,
    nombre: "Ana",
    apellido: "Martínez",
    edad: 42,
    genero: "Femenino",
    email: "ana.martinez@example.com",
    telefono: "1134567890",
    direccion: "Mitre 789",
    ciudad: "Rosario",
    pais: "Argentina",
    estadoCivil: "Divorciada",
    profesion: "Docente"
  },
  {
    id: 4,
    nombre: "Carlos",
    apellido: "López",
    edad: 29,
    genero: "Masculino",
    email: "carlos.lopez@example.com",
    telefono: "1145678901",
    direccion: "Belgrano 1023",
    ciudad: "La Plata",
    pais: "Argentina",
    estadoCivil: "Soltero",
    profesion: "Abogado"
  },
  {
    id: 5,
    nombre: "Mariana",
    apellido: "Díaz",
    edad: 33,
    genero: "Femenino",
    email: "mariana.diaz@example.com",
    telefono: "1156789012",
    direccion: "San Martín 456",
    ciudad: "Mendoza",
    pais: "Argentina",
    estadoCivil: "Casada",
    profesion: "Médica"
  },
  {
    id: 6,
    nombre: "Pedro",
    apellido: "Fernández",
    edad: 40,
    genero: "Masculino",
    email: "pedro.fernandez@example.com",
    telefono: "1167890123",
    direccion: "Alsina 789",
    ciudad: "Salta",
    pais: "Argentina",
    estadoCivil: "Casado",
    profesion: "Contador"
  },
  {
    id: 7,
    nombre: "Valeria",
    apellido: "Suárez",
    edad: 31,
    genero: "Femenino",
    email: "valeria.suarez@example.com",
    telefono: "1178901234",
    direccion: "Independencia 234",
    ciudad: "Santa Fe",
    pais: "Argentina",
    estadoCivil: "Soltera",
    profesion: "Psicóloga"
  },
  {
    id: 8,
    nombre: "Diego",
    apellido: "Mendoza",
    edad: 45,
    genero: "Masculino",
    email: "diego.mendoza@example.com",
    telefono: "1189012345",
    direccion: "Av. Colón 678",
    ciudad: "Neuquén",
    pais: "Argentina",
    estadoCivil: "Viudo",
    profesion: "Arquitecto"
  },
  {
    id: 9,
    nombre: "Florencia",
    apellido: "Ramírez",
    edad: 26,
    genero: "Femenino",
    email: "florencia.ramirez@example.com",
    telefono: "1190123456",
    direccion: "9 de Julio 321",
    ciudad: "Tucumán",
    pais: "Argentina",
    estadoCivil: "Soltera",
    profesion: "Periodista"
  },
  {
    id: 10,
    nombre: "Santiago",
    apellido: "Moreno",
    edad: 38,
    genero: "Masculino",
    email: "santiago.moreno@example.com",
    telefono: "1101234567",
    direccion: "Lavalle 1234",
    ciudad: "San Juan",
    pais: "Argentina",
    estadoCivil: "Casado",
    profesion: "Desarrollador"
  },
  {
    id: 11,
    nombre: "Jazmín",
    apellido: "Herrera",
    edad: 30,
    genero: "Femenino",
    email: "jazmin.herrera@example.com",
    telefono: "1123459876",
    direccion: "Italia 678",
    ciudad: "Resistencia",
    pais: "Argentina",
    estadoCivil: "Soltera",
    profesion: "Farmacéutica"
  },
  {
    id: 12,
    nombre: "Matías",
    apellido: "Rojas",
    edad: 36,
    genero: "Masculino",
    email: "matias.rojas@example.com",
    telefono: "1123981234",
    direccion: "España 222",
    ciudad: "Formosa",
    pais: "Argentina",
    estadoCivil: "Casado",
    profesion: "Electricista"
  },
  {
    id: 13,
    nombre: "Camila",
    apellido: "Silva",
    edad: 24,
    genero: "Femenino",
    email: "camila.silva@example.com",
    telefono: "1134567891",
    direccion: "Chile 789",
    ciudad: "San Luis",
    pais: "Argentina",
    estadoCivil: "Soltera",
    profesion: "Estudiante"
  },
  {
    id: 14,
    nombre: "Bruno",
    apellido: "García",
    edad: 41,
    genero: "Masculino",
    email: "bruno.garcia@example.com",
    telefono: "1145678902",
    direccion: "Catamarca 654",
    ciudad: "Jujuy",
    pais: "Argentina",
    estadoCivil: "Casado",
    profesion: "Veterinario"
  },
  {
    id: 15,
    nombre: "Martina",
    apellido: "Castro",
    edad: 37,
    genero: "Femenino",
    email: "martina.castro@example.com",
    telefono: "1156789023",
    direccion: "Misiones 321",
    ciudad: "Posadas",
    pais: "Argentina",
    estadoCivil: "Divorciada",
    profesion: "Chef"
  },
  {
    id: 16,
    nombre: "Agustín",
    apellido: "Ortega",
    edad: 34,
    genero: "Masculino",
    email: "agustin.ortega@example.com",
    telefono: "1167890124",
    direccion: "Entre Ríos 101",
    ciudad: "Paraná",
    pais: "Argentina",
    estadoCivil: "Soltero",
    profesion: "Analista de datos"
  },
  {
    id: 17,
    nombre: "Paula",
    apellido: "Reyes",
    edad: 29,
    genero: "Femenino",
    email: "paula.reyes@example.com",
    telefono: "1178901235",
    direccion: "La Rioja 404",
    ciudad: "Santiago del Estero",
    pais: "Argentina",
    estadoCivil: "Soltera",
    profesion: "Nutricionista"
  },
  {
    id: 18,
    nombre: "Nicolás",
    apellido: "Ibarra",
    edad: 32,
    genero: "Masculino",
    email: "nicolas.ibarra@example.com",
    telefono: "1189012346",
    direccion: "Corrientes 900",
    ciudad: "Corrientes",
    pais: "Argentina",
    estadoCivil: "Casado",
    profesion: "Programador"
  },
  {
    id: 19,
    nombre: "Romina",
    apellido: "Vega",
    edad: 27,
    genero: "Femenino",
    email: "romina.vega@example.com",
    telefono: "1190123457",
    direccion: "Santa Fe 111",
    ciudad: "Santa Rosa",
    pais: "Argentina",
    estadoCivil: "Soltera",
    profesion: "Diseñadora UX"
  },
  {
    id: 20,
    nombre: "Facundo",
    apellido: "Navarro",
    edad: 44,
    genero: "Masculino",
    email: "facundo.navarro@example.com",
    telefono: "1101234568",
    direccion: "Av. Libertador 123",
    ciudad: "Rio Gallegos",
    pais: "Argentina",
    estadoCivil: "Casado",
    profesion: "Gerente de proyectos"
  },
  {
    id: 21,
    nombre: "Sofía",
    apellido: "Leiva",
    edad: 39,
    genero: "Femenino",
    email: "sofia.leiva@example.com",
    telefono: "1123011223",
    direccion: "Roca 234",
    ciudad: "Bariloche",
    pais: "Argentina",
    estadoCivil: "Casada",
    profesion: "Enfermera"
  },
  {
    id: 22,
    nombre: "Tomás",
    apellido: "Molina",
    edad: 25,
    genero: "Masculino",
    email: "tomas.molina@example.com",
    telefono: "1134563322",
    direccion: "Güemes 234",
    ciudad: "San Rafael",
    pais: "Argentina",
    estadoCivil: "Soltero",
    profesion: "Fotógrafo"
  },
  {
    id: 23,
    nombre: "Malena",
    apellido: "Ruiz",
    edad: 36,
    genero: "Femenino",
    email: "malena.ruiz@example.com",
    telefono: "1145678832",
    direccion: "Junín 678",
    ciudad: "Catamarca",
    pais: "Argentina",
    estadoCivil: "Divorciada",
    profesion: "Investigadora"
  },
  {
    id: 24,
    nombre: "Leo",
    apellido: "Barrios",
    edad: 43,
    genero: "Masculino",
    email: "leo.barrios@example.com",
    telefono: "1156789111",
    direccion: "Chacabuco 300",
    ciudad: "San Fernando del Valle",
    pais: "Argentina",
    estadoCivil: "Casado",
    profesion: "Técnico en redes"
  },
  {
    id: 25,
    nombre: "Bárbara",
    apellido: "Luna",
    edad: 31,
    genero: "Femenino",
    email: "barbara.luna@example.com",
    telefono: "1167890222",
    direccion: "Francia 455",
    ciudad: "Ushuaia",
    pais: "Argentina",
    estadoCivil: "Soltera",
    profesion: "Traductora"
  },
  {
    id: 26,
    nombre: "Ezequiel",
    apellido: "Campos",
    edad: 27,
    genero: "Masculino",
    email: "ezequiel.campos@example.com",
    telefono: "1178901444",
    direccion: "Brasil 889",
    ciudad: "Trelew",
    pais: "Argentina",
    estadoCivil: "Soltero",
    profesion: "Diseñador web"
  },
  {
    id: 27,
    nombre: "Celeste",
    apellido: "Acosta",
    edad: 40,
    genero: "Femenino",
    email: "celeste.acosta@example.com",
    telefono: "1189012999",
    direccion: "Bolivia 100",
    ciudad: "Rawson",
    pais: "Argentina",
    estadoCivil: "Casada",
    profesion: "Gestora cultural"
  },
  {
    id: 28,
    nombre: "Iván",
    apellido: "Muñoz",
    edad: 30,
    genero: "Masculino",
    email: "ivan.munoz@example.com",
    telefono: "1190123111",
    direccion: "Perú 333",
    ciudad: "Villa María",
    pais: "Argentina",
    estadoCivil: "Soltero",
    profesion: "Consultor"
  },
  {
    id: 29,
    nombre: "Milagros",
    apellido: "Sánchez",
    edad: 35,
    genero: "Femenino",
    email: "milagros.sanchez@example.com",
    telefono: "1101234777",
    direccion: "Honduras 255",
    ciudad: "San Nicolás",
    pais: "Argentina",
    estadoCivil: "Casada",
    profesion: "Maestra jardinera"
  },
  {
    id: 30,
    nombre: "Franco",
    apellido: "Delgado",
    edad: 38,
    genero: "Masculino",
    email: "franco.delgado@example.com",
    telefono: "1123450000",
    direccion: "Uruguay 765",
    ciudad: "Bahía Blanca",
    pais: "Argentina",
    estadoCivil: "Casado",
    profesion: "Administrativo"
  }
];